### ISSUE TITLE
Consider IANA registration of URI Scheme for ssb?

### ISSUE THREAD

**Issue by fred-wang** [ssbc/ssb-spec-drafts#4]
Apologies if I'm reporting to the wrong repository. I personally can't find any mention of ssb URI scheme but @lidel requested to add ssb to the list of protocol recognized by registerProtocolHandler():

https://github.com/whatwg/html/issues/3935

I was suggested to register to IANA, see
https://github.com/whatwg/html/pull/5482#issuecomment-618973427
https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml
https://tools.ietf.org/html/rfc7595

**Comment by christianbundy** [comment]
Hi! Here's a link to the SSB-URI repository: https://github.com/fraction/ssb-uri

Is that helpful, or are you looking for more info? Please feel free to ping me directly if you're trying to find the right repo for something -- most of us only have notifications on for a few repos so it's easy for stuff like this to fall through the cracks.

**Comment by fred-wang** [comment]
@christianbundy Thanks. It seems this repository is for an utility to convert to/from URI. Is there any standard/specification for ssb when such URIs are defined? I'm basically looking to whom I should coordinate with to register `ssb:` to IANA and I guess I'd need a spec reference in any case.

**Comment by fred-wang** [comment]
https://raw.githubusercontent.com/fred-wang/iana-uri-schemes-provisional-registration-requests/master/ssb.txt

(I'm going to follow-up by email)

**Comment by fred-wang** [comment]
Registration request sent.

**Comment by fred-wang** [comment]
... and approved: https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml
